#!/usr/bin/env python3

# unse only every X trees (1 for all)
use_trees = 7

# individual tree rotation (radiant)
tree_rotation = 3.14159

# tree hight from radius factor
tree_hight_factor = 32

with open("./tree_positions.csv", "r") as f:
    lines = f.readlines()

SDF = """<?xml version="1.0" ?>
<!-- auto generated by generate_model_sdf.py -->
<sdf version="1.10">

<model name="lehrforst_trees">

<static>true</static>
"""
for i, line in enumerate(lines[1:]):
    if i % use_trees:
        continue
    x, y, z, w = map(float, line.split(','))
    radius = round(w * 0.005, 3)
    SDF +=f"""
  <link name='tree_{i+1:0>4}'>
    <pose>{x} {y} {z} {tree_rotation} 0 0</pose>
    <visual name='visual'>
      <geometry>
        <cylinder>
          <radius>{radius:.3f}</radius>
          <length>{tree_hight_factor*radius:.3f}</length>
        </cylinder>
      </geometry>
      <material>
        <ambient>0.42 0.29 0.19 1</ambient>
        <diffuse>0.42 0.29 0.19 1</diffuse>
        <specular>0.42 0.29 0.19 1</specular>
      </material>
    </visual>
    <collision name='collision'>
      <geometry>
        <cylinder>
          <radius>{radius:.3f}</radius>
          <length>{tree_hight_factor*radius:.3f}</length>
        </cylinder>
      </geometry>
    </collision>
  </link>
"""
SDF += """
</model>

</sdf>"""

with open("./model.sdf", "w") as f:
    f.write(SDF)
