#!/usr/bin/env python3

# unse only every X trees (1 for all)
use_trees = 7

# individual tree rotation (radiant)
tree_rotation = 3.14159

with open("./tree_positions.csv", "r") as f:
    lines = f.readlines()

SDF = """<?xml version="1.0" ?>
<!-- auto generated by generate_model_sdf.py -->
<sdf version="1.10">
<model name="lehrforst_trees">
<static>true</static>
"""
for i, line in enumerate(lines[1:]):
    if i % use_trees:
        continue
    x, y, z = map(float, line.split(',')[:3])
    SDF +=f"<include><uri>models/pine_tree</uri><name>pine_{i+1:0>4}</name><pose>{x} {y} {z} {tree_rotation} 0 0</pose></include>\n"
SDF += "</model>\n</sdf>"

with open("./model.sdf", "w") as f:
    f.write(SDF)
