#!/usr/bin/env python3

"""Generates model.sdf for the lehrforst trees out of the provided .csv"""

import os
import random
import math

model_path = os.path.dirname(__file__)

# wether to use nice tree models or not
fancy = True

# area in which trees will be loaded
x_min = 10
x_max = 70
y_min = -30
y_max = 30

# unse only every X trees (1 for all)
use_trees = 1

# use only trees with diamater X (cm) or larger (0 for all)
min_diam = 7#cm

# individual tree rotation (radiant)
tree_rotation = math.pi

# tree hight from radius factor
tree_hight_factor = 16

with open(f"{model_path}/tree_positions.csv", "r") as f:
    lines = f.readlines()

CSV = ''
SDF = """<?xml version="1.0" ?>
<!-- auto generated by generate_model_sdf.py -->
<sdf version="1.10">

<model name="lehrforst_trees">

<static>true</static>
"""
for i, line in enumerate(lines[1:]):
    x, y, z, w = map(float, line.split(','))
    if w < min_diam or i % use_trees or \
      not x_min < x < x_max or not y_min < y < y_max:
        continue
    CSV += f"{x},{y},{z},{w}\n"
    radius = w * 0.01 # convert from cm (/100)
    scale = w / 12  # normalize to median tree trunk width
    random_rotation_z = random.uniform(0, 2*math.pi)
    random_rotation_y = random.uniform(0, 0.075)

    if fancy:
  # <collision name="tree_{i+1:0>4}_collision">
  #   <pose relative_to='world'>{x:.3f} {y:.3f} {z:.3f} {tree_rotation:.3f} {random_rotation_y:.3f} {random_rotation_z:.3f}</pose>
  #   <geometry>
  #     <mesh>
  #       <scale>{scale:.3f} {scale:.3f} {scale:.3f}</scale>
  #       <uri>meshes/pine_tree.dae</uri>
  #     </mesh>
  #   </geometry>
  # </collision>
      SDF += f"""
  <link name='tree_{i+1:0>4}'>
    <collision name='tree_{i+1:0>4}_collision'>
      <pose>{x:.3f} {y:.3f} {z-tree_hight_factor*radius/2+0.1:.3f} {tree_rotation:.3f} {random_rotation_y/2:.3f} 0</pose>
      <geometry>
        <cone>
          <radius>{radius:.3f}</radius>
          <length>{tree_hight_factor*radius:.3f}</length>
        </cone>
      </geometry>
    </collision>
    <visual name="tree_{i+1:0>4}_branch">
      <pose relative_to='world'>{x:.3f} {y:.3f} {z:.3f} {tree_rotation:.3f} {random_rotation_y:.3f} {random_rotation_z:.3f}</pose>
      <geometry>
        <mesh>
          <scale>{scale:.3f} {scale:.3f} {scale:.3f}</scale>
          <uri>meshes/pine_tree.dae</uri>
          <submesh>
            <name>Branch</name>
          </submesh>
        </mesh>
      </geometry>
      <material>
        <double_sided>true</double_sided>
        <diffuse>1.0 1.0 1.0</diffuse>
        <script>
          <uri>materials/scripts/</uri>
          <uri>materials/textures/</uri>
          <name>PineTree/Branch</name>
        </script>
        <pbr>
          <metal>
            <albedo_map>materials/textures/branch_2_diffuse.png</albedo_map>
          </metal>
        </pbr>
      </material>
    </visual>
    <visual name="tree_{i+1:0>4}_bark">
      <pose relative_to='world'>{x:.3f} {y:.3f} {z:.3f} {tree_rotation:.3f} {random_rotation_y:.3f} {random_rotation_z:.3f}</pose>
      <geometry>
        <mesh>
          <scale>{scale:.3f} {scale:.3f} {scale:.3f}</scale>
          <uri>meshes/pine_tree.dae</uri>
          <submesh>
            <name>Bark</name>
          </submesh>
        </mesh>
      </geometry>
      <material>
        <diffuse>1.0 1.0 1.0</diffuse>
        <script>
          <uri>materials/scripts/</uri>
          <uri>materials/textures/</uri>
          <name>PineTree/Bark</name>
        </script>
        <pbr>
          <metal>
            <albedo_map>materials/textures/bark_diffuse.png</albedo_map>
          </metal>
        </pbr>
      </material>
    </visual>
  </link>
"""

    else:
      SDF += f"""
  <link name='tree_{i+1:0>4}'>
    <collision name='tree_{i+1:0>4}_collision'>
      <pose>{x:.3f} {y:.3f} {z-tree_hight_factor*radius/2+0.1:.3f} {tree_rotation:.3f} {random_rotation_y/2:.3f} 0</pose>
      <geometry>
        <cone>
          <radius>{radius:.3f}</radius>
          <length>{tree_hight_factor*radius:.3f}</length>
        </cone>
      </geometry>
    </collision>
    <visual name='tree_{i+1:0>4}_trunk'>
      <pose>{x:.3f} {y:.3f} {z-tree_hight_factor*radius/2+0.1:.3f} {tree_rotation:.3f} {random_rotation_y/2:.3f} 0</pose>
      <geometry>
        <cone>
          <radius>{radius:.3f}</radius>
          <length>{tree_hight_factor*radius:.3f}</length>
        </cone>
      </geometry>
      <material>
        <ambient>0.42 0.29 0.19 1</ambient>
        <diffuse>0.42 0.29 0.19 1</diffuse>
        <specular>0.42 0.29 0.19 1</specular>
      </material>
    </visual>
    <visual name='tree_{i+1:0>4}_leaves'>
      <pose>{x:.3f} {y:.3f} {z-1.5*tree_hight_factor*radius+0.1:.3f} {tree_rotation:.3f} 0 0</pose>
      <geometry>
        <cone>
          <radius>{5*radius:.3f}</radius>
          <length>{30*radius:.3f}</length>
        </cone>
      </geometry>
      <material>
        <ambient>0.14 0.40 0.07 1</ambient>
        <diffuse>0.14 0.40 0.07 1</diffuse>
        <specular>0.14 0.40 0.07 1</specular>
      </material>
    </visual>
  </link>
"""

SDF += """
</model>

</sdf>"""

with open(f"{model_path}/model.sdf", "w") as f:
    f.write(SDF)

with open(f"{model_path}/tree_position_filtered.csv", "w") as f:
    f.write(CSV)
